import pandas as pd

books = [
    # ACOTAR Series
    {
        "book_id": 1,
        "title": "A Court of Thorns and Roses",
        "author": "Sarah J. Maas",
        "series": "ACOTAR",
        "series_position": 1,
        "genre": "Romantasy",
        "my_rating": 5,
        "avg_rating": 4.14,
        "date_read": "2021-03-01",
        "spice_level": 2,
        "page_count": 419,
        "rep": None,
        "format": "paperback",
        "owned": True,
        "notes": "The one that started it all. Fae retelling of Beauty and the Beast."
    },
    {
        "book_id": 2,
        "title": "A Court of Mist and Fury",
        "author": "Sarah J. Maas",
        "series": "ACOTAR",
        "series_position": 2,
        "genre": "Romantasy",
        "my_rating": 5,
        "avg_rating": 4.57,
        "date_read": "2021-03-15",
        "spice_level": 4,
        "page_count": 626,
        "rep": None,
        "format": "paperback",
        "owned": True,
        "notes": "Rhysand. That's it. That's the note."
    },
    {
        "book_id": 3,
        "title": "A Court of Wings and Ruin",
        "author": "Sarah J. Maas",
        "series": "ACOTAR",
        "series_position": 3,
        "genre": "Romantasy",
        "my_rating": 4,
        "avg_rating": 4.27,
        "date_read": "2021-04-01",
        "spice_level": 4,
        "page_count": 699,
        "rep": None,
        "format": "paperback",
        "owned": True,
        "notes": "Epic conclusion but slightly bloated."
    },
    {
        "book_id": 4,
        "title": "A Court of Frost and Starlight",
        "author": "Sarah J. Maas",
        "series": "ACOTAR",
        "series_position": 4,
        "genre": "Romantasy",
        "my_rating": 3,
        "avg_rating": 3.94,
        "date_read": "2021-04-10",
        "spice_level": 3,
        "page_count": 229,
        "rep": None,
        "format": "ebook",
        "owned": True,
        "notes": "Cozy novella vibes. Not much plot."
    },
    {
        "book_id": 5,
        "title": "A Court of Silver Flames",
        "author": "Sarah J. Maas",
        "series": "ACOTAR",
        "series_position": 5,
        "genre": "Romantasy",
        "my_rating": 5,
        "avg_rating": 4.32,
        "date_read": "2021-05-01",
        "spice_level": 5,
        "page_count": 757,
        "rep": None,
        "format": "hardcover",
        "owned": True,
        "notes": "Nesta arc was everything. Spicy and fierce."
    },
    # Throne of Glass Series
    {
        "book_id": 6,
        "title": "Throne of Glass",
        "author": "Sarah J. Maas",
        "series": "Throne of Glass",
        "series_position": 1,
        "genre": "Romantasy",
        "my_rating": 4,
        "avg_rating": 4.03,
        "date_read": "2021-06-01",
        "spice_level": 1,
        "page_count": 404,
        "rep": None,
        "format": "paperback",
        "owned": True,
        "notes": "Assassin queen energy. Younger SJM but still fun."
    },
    {
        "book_id": 7,
        "title": "Crown of Midnight",
        "author": "Sarah J. Maas",
        "series": "Throne of Glass",
        "series_position": 2,
        "genre": "Romantasy",
        "my_rating": 4,
        "avg_rating": 4.24,
        "date_read": "2021-06-15",
        "spice_level": 2,
        "page_count": 418,
        "rep": None,
        "format": "paperback",
        "owned": True,
        "notes": "Series really picks up here."
    },
    {
        "book_id": 8,
        "title": "Heir of Fire",
        "author": "Sarah J. Maas",
        "series": "Throne of Glass",
        "series_position": 3,
        "genre": "Romantasy",
        "my_rating": 5,
        "avg_rating": 4.36,
        "date_read": "2021-07-01",
        "spice_level": 2,
        "page_count": 565,
        "rep": None,
        "format": "paperback",
        "owned": True,
        "notes": "Rowan enters. Game over."
    },
    {
        "book_id": 9,
        "title": "Queen of Shadows",
        "author": "Sarah J. Maas",
        "series": "Throne of Glass",
        "series_position": 4,
        "genre": "Romantasy",
        "my_rating": 5,
        "avg_rating": 4.41,
        "date_read": "2021-07-20",
        "spice_level": 2,
        "page_count": 648,
        "rep": None,
        "format": "paperback",
        "owned": True,
        "notes": "Peak Celaena energy."
    },
    {
        "book_id": 10,
        "title": "Empire of Storms",
        "author": "Sarah J. Maas",
        "series": "Throne of Glass",
        "series_position": 5,
        "genre": "Romantasy",
        "my_rating": 5,
        "avg_rating": 4.44,
        "date_read": "2021-08-01",
        "spice_level": 4,
        "page_count": 689,
        "rep": None,
        "format": "paperback",
        "owned": True,
        "notes": "Things get spicy and epic."
    },
    {
        "book_id": 11,
        "title": "Tower of Dawn",
        "author": "Sarah J. Maas",
        "series": "Throne of Glass",
        "series_position": 6,
        "genre": "Romantasy",
        "my_rating": 4,
        "avg_rating": 4.25,
        "date_read": "2021-08-15",
        "spice_level": 3,
        "page_count": 660,
        "rep": None,
        "format": "paperback",
        "owned": True,
        "notes": "Chaol's redemption arc. Slow start but worth it."
    },
    {
        "book_id": 12,
        "title": "Kingdom of the Wicked",
        "author": "Sarah J. Maas",
        "series": "Throne of Glass",
        "series_position": 7,
        "genre": "Romantasy",
        "my_rating": 5,
        "avg_rating": 4.51,
        "date_read": "2021-09-01",
        "spice_level": 4,
        "page_count": 980,
        "rep": None,
        "format": "hardcover",
        "owned": True,
        "notes": "The finale we deserved. Absolutely epic."
    },
    # Crescent City Series
    {
        "book_id": 13,
        "title": "House of Earth and Blood",
        "author": "Sarah J. Maas",
        "series": "Crescent City",
        "series_position": 1,
        "genre": "Romantasy",
        "my_rating": 5,
        "avg_rating": 4.20,
        "date_read": "2022-01-01",
        "spice_level": 4,
        "page_count": 803,
        "rep": None,
        "format": "hardcover",
        "owned": True,
        "notes": "Urban fantasy SJM. Hunt Athalar is everything."
    },
    {
        "book_id": 14,
        "title": "House of Sky and Breath",
        "author": "Sarah J. Maas",
        "series": "Crescent City",
        "series_position": 2,
        "genre": "Romantasy",
        "my_rating": 4,
        "avg_rating": 4.25,
        "date_read": "2022-03-01",
        "spice_level": 4,
        "page_count": 803,
        "rep": None,
        "format": "hardcover",
        "owned": True,
        "notes": "Slow middle but the ending destroyed me."
    },
    {
        "book_id": 15,
        "title": "House of Flame and Shadow",
        "author": "Sarah J. Maas",
        "series": "Crescent City",
        "series_position": 3,
        "genre": "Romantasy",
        "my_rating": 4,
        "avg_rating": 4.18,
        "date_read": "2024-02-01",
        "spice_level": 4,
        "page_count": 896,
        "rep": None,
        "format": "hardcover",
        "owned": True,
        "notes": "Wild crossover chaos. Divisive but I loved it."
    },
    # The Poppy War
    {
        "book_id": 16,
        "title": "The Poppy War",
        "author": "R.F. Kuang",
        "series": None,
        "series_position": None,
        "genre": "Grimdark Fantasy",
        "my_rating": 5,
        "avg_rating": 4.10,
        "date_read": "2022-06-01",
        "spice_level": 0,
        "page_count": 545,
        "rep": "Asian rep",
        "format": "paperback",
        "owned": True,
        "notes": "Brutal, brilliant, unlike anything else. Not romantasy but unforgettable."
    },
    # Zodiac Academy
    {
        "book_id": 17,
        "title": "Zodiac Academy: The Awakening",
        "author": "Caroline Peckham & Susanne Valenti",
        "series": "Zodiac Academy",
        "series_position": 1,
        "genre": "Romantasy",
        "my_rating": 4,
        "avg_rating": 4.22,
        "date_read": "2023-01-01",
        "spice_level": 3,
        "page_count": 532,
        "rep": None,
        "format": "ebook",
        "owned": True,
        "notes": "Chaotic bully romance energy. Addictive."
    },
    {
        "book_id": 18,
        "title": "Zodiac Academy: Ruthless Fae",
        "author": "Caroline Peckham & Susanne Valenti",
        "series": "Zodiac Academy",
        "series_position": 2,
        "genre": "Romantasy",
        "my_rating": 4,
        "avg_rating": 4.35,
        "date_read": "2023-01-15",
        "spice_level": 3,
        "page_count": 591,
        "rep": None,
        "format": "ebook",
        "owned": True,
        "notes": "The Heirs are insufferable and I love them."
    },
    {
        "book_id": 19,
        "title": "Zodiac Academy: The Reckoning",
        "author": "Caroline Peckham & Susanne Valenti",
        "series": "Zodiac Academy",
        "series_position": 3,
        "genre": "Romantasy",
        "my_rating": 4,
        "avg_rating": 4.43,
        "date_read": "2023-02-01",
        "spice_level": 4,
        "page_count": 618,
        "rep": None,
        "format": "ebook",
        "owned": True,
        "notes": "Things get darker and spicier."
    },
    {
        "book_id": 20,
        "title": "Zodiac Academy: Shadow Princess",
        "author": "Caroline Peckham & Susanne Valenti",
        "series": "Zodiac Academy",
        "series_position": 4,
        "genre": "Romantasy",
        "my_rating": 5,
        "avg_rating": 4.51,
        "date_read": "2023-02-20",
        "spice_level": 4,
        "page_count": 656,
        "rep": None,
        "format": "ebook",
        "owned": True,
        "notes": "Darcy and Orion. My heart."
    },
]

df = pd.DataFrame(books)
df.to_csv("data/sample_books.csv", index=False)
print(f"✅ Saved {len(df)} books to data/sample_books.csv")
print(df[["title", "author", "my_rating", "spice_level"]].to_string())